<#include "master_mail.ftlh">

<#macro title>Your offer completed with no bids</#macro>
<#macro greeting>Dear, ${name}!</#macro>
<#macro maintext>Please, pay attention, that your offer completed with no bids. You can check the offer with this link <a href="${link}">offer</a>.<br/>Maybe, you need to decrease start price, change content of your offer to make it more interesting for the participants.</#macro>

<@content/>