<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Your offer completed with no bids</title>
</head>
<body>
<h1 style="color: green">Your offer completed with no bids</h1>
<h2>Dear, ${name}!</h2>
<p>Please, pay attention, that your offer completed with no bids. You can check the offer with this link <a href="${link}">offer</a>.
    Maybe, you need to decrease start price, change content of your offer to make it more interesting for the participants.
</p>
</body>
</html>
